services:
  nginx:
    image: nginx:alpine
    container_name: frontend-app
    ports:
      - "8080:80" 
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped